[package]
name = "rustyled"
version = "0.1.0"
edition = "2021"

[dependencies]
bdf = "0.6.0"
chrono = "0.4.34"
minifb = "0.25.0"

[target.'cfg(target_arch = "arm")'.dependencies.rpi-led-matrix]
version = "0.4.0"
